### ISSUE TITLE
how can I get tsdf file from ply pointcloud?

### ISSUE THREAD

**Issue by yaoyishen** [VVingerfly/surfRecon#3]
I am confused that where the tsdf file comes from?And can I change a ply pointcloud to a tsdf file?

**Comment by VVingerfly** [comment]
The tsdf files are generated by KinectFusion. If you want to generate tsdf from pointcloud, you can try to use Poisson Reconstruction to get a triangle mesh first, then sample grid in the bounding box of the mesh and compute signed distance for each grid.

**Comment by yaoyishen** [comment]
> The tsdf files are generated by KinectFusion. If you want to generate tsdf from pointcloud, you can try to use Poisson Reconstruction to get a triangle mesh first, then sample grid in the bounding box of the mesh and compute signed distance for each grid.

thank you for your reply
